# Generated by Django 2.1.7 on 2019-04-27 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aurora_application', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='img',
            old_name='img_url',
            new_name='img',
        ),
    ]
